# Generated by Django 2.2.4 on 2019-09-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='add_date',
            new_name='added_date',
        ),
    ]
